version: '2'

services:

  app:
    image: node
    working_dir: /usr/src/app
    ports:
      - "8080:3000"
    volumes:
      - $PWD:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c 'npm install && npm run dev'

  db:
    image: mongo
